<?php

namespace Database\Seeders;

use App\Models\CategoriaProducto;
use App\Models\Producto;
use App\Models\TarifaIva;
use App\Models\UnidadMedida;
use Illuminate\Database\Seeder;

class ProductoSeeder extends Seeder
{
    public function run(): void
    {
        $un  = UnidadMedida::where('abreviatura', 'UN')->first();
        $kg  = UnidadMedida::where('abreviatura', 'KG')->first();
        $lt  = UnidadMedida::where('abreviatura', 'L')->first();
        $ml  = UnidadMedida::where('abreviatura', 'ML')->first();
        $g   = UnidadMedida::where('abreviatura', 'G')->first();

        $iva19   = TarifaIva::where('nombre', 'IVA 19%')->first();
        $iva5    = TarifaIva::where('nombre', 'IVA 5%')->first();
        $exento  = TarifaIva::where('nombre', 'Exento')->first();
        $excluido = TarifaIva::where('nombre', 'Excluido')->first();

        // Category lookups
        $cat = fn(string $nombre) => CategoriaProducto::where('nombre', $nombre)->first();

        $productos = [
            // ── Lácteos y Huevos ─────────────────────────────────────────
            [
                'codigo'         => 'LAC001',
                'codigo_barras'  => '7702001000018',
                'nombre'         => 'Leche Entera Alquería 1L',
                'categoria'      => 'Lácteos y Huevos',
                'unidad'         => $lt,
                'iva'            => $exento,
                'precio_compra'  => 2800,
                'precio_venta'   => 3500,
                'stock_actual'   => 120,
                'stock_minimo'   => 24,
            ],
            [
                'codigo'        => 'LAC002',
                'codigo_barras' => '7702001000025',
                'nombre'        => 'Leche Deslactosada Alpina 900ml',
                'categoria'     => 'Lácteos y Huevos',
                'unidad'        => $ml,
                'iva'           => $exento,
                'precio_compra' => 3200,
                'precio_venta'  => 4200,
                'stock_actual'  => 80,
                'stock_minimo'  => 20,
            ],
            [
                'codigo'        => 'LAC003',
                'codigo_barras' => '7702001000032',
                'nombre'        => 'Yogurt Alpina Fresa 200g',
                'categoria'     => 'Lácteos y Huevos',
                'unidad'        => $g,
                'iva'           => $exento,
                'precio_compra' => 1200,
                'precio_venta'  => 1800,
                'stock_actual'  => 60,
                'stock_minimo'  => 12,
            ],
            [
                'codigo'        => 'LAC004',
                'codigo_barras' => '7702001000049',
                'nombre'        => 'Queso Campesino 500g',
                'categoria'     => 'Lácteos y Huevos',
                'unidad'        => $g,
                'iva'           => $exento,
                'precio_compra' => 6500,
                'precio_venta'  => 9500,
                'stock_actual'  => 30,
                'stock_minimo'  => 10,
            ],
            [
                'codigo'        => 'LAC005',
                'codigo_barras' => '7702001000056',
                'nombre'        => 'Huevos AA x12',
                'categoria'     => 'Lácteos y Huevos',
                'unidad'        => $un,
                'iva'           => $excluido,
                'precio_compra' => 7500,
                'precio_venta'  => 10500,
                'stock_actual'  => 50,
                'stock_minimo'  => 10,
            ],
            [
                'codigo'        => 'LAC006',
                'codigo_barras' => '7702001000063',
                'nombre'        => 'Mantequilla Con Sal 250g',
                'categoria'     => 'Lácteos y Huevos',
                'unidad'        => $g,
                'iva'           => $exento,
                'precio_compra' => 4200,
                'precio_venta'  => 5900,
                'stock_actual'  => 40,
                'stock_minimo'  => 8,
            ],

            // ── Granos y Cereales ─────────────────────────────────────────
            [
                'codigo'        => 'GRA001',
                'codigo_barras' => '7703001000011',
                'nombre'        => 'Arroz Diana 500g',
                'categoria'     => 'Granos y Cereales',
                'unidad'        => $g,
                'iva'           => $excluido,
                'precio_compra' => 1800,
                'precio_venta'  => 2800,
                'stock_actual'  => 200,
                'stock_minimo'  => 50,
            ],
            [
                'codigo'        => 'GRA002',
                'codigo_barras' => '7703001000028',
                'nombre'        => 'Arroz Diana 2kg',
                'categoria'     => 'Granos y Cereales',
                'unidad'        => $kg,
                'iva'           => $excluido,
                'precio_compra' => 6500,
                'precio_venta'  => 9200,
                'stock_actual'  => 150,
                'stock_minimo'  => 30,
            ],
            [
                'codigo'        => 'GRA003',
                'codigo_barras' => '7703001000035',
                'nombre'        => 'Frijol Cargamanto 500g',
                'categoria'     => 'Granos y Cereales',
                'unidad'        => $g,
                'iva'           => $excluido,
                'precio_compra' => 2200,
                'precio_venta'  => 3400,
                'stock_actual'  => 100,
                'stock_minimo'  => 20,
            ],
            [
                'codigo'        => 'GRA004',
                'codigo_barras' => '7703001000042',
                'nombre'        => 'Lenteja Verde 500g',
                'categoria'     => 'Granos y Cereales',
                'unidad'        => $g,
                'iva'           => $excluido,
                'precio_compra' => 2000,
                'precio_venta'  => 3200,
                'stock_actual'  => 80,
                'stock_minimo'  => 15,
            ],
            [
                'codigo'        => 'GRA005',
                'codigo_barras' => '7703001000059',
                'nombre'        => 'Espagueti La Muñeca 400g',
                'categoria'     => 'Granos y Cereales',
                'unidad'        => $g,
                'iva'           => $excluido,
                'precio_compra' => 2500,
                'precio_venta'  => 3600,
                'stock_actual'  => 120,
                'stock_minimo'  => 24,
            ],
            [
                'codigo'        => 'GRA006',
                'codigo_barras' => '7703001000066',
                'nombre'        => 'Avena en Hojuelas 400g',
                'categoria'     => 'Granos y Cereales',
                'unidad'        => $g,
                'iva'           => $excluido,
                'precio_compra' => 3000,
                'precio_venta'  => 4500,
                'stock_actual'  => 60,
                'stock_minimo'  => 12,
            ],

            // ── Condimentos y Salsas ──────────────────────────────────────
            [
                'codigo'        => 'CON001',
                'codigo_barras' => '7704001000017',
                'nombre'        => 'Aceite Girasol 900ml',
                'categoria'     => 'Condimentos y Salsas',
                'unidad'        => $ml,
                'iva'           => $excluido,
                'precio_compra' => 9500,
                'precio_venta'  => 13500,
                'stock_actual'  => 80,
                'stock_minimo'  => 12,
            ],
            [
                'codigo'        => 'CON002',
                'codigo_barras' => '7704001000024',
                'nombre'        => 'Azúcar Blanca 1kg',
                'categoria'     => 'Condimentos y Salsas',
                'unidad'        => $kg,
                'iva'           => $excluido,
                'precio_compra' => 2800,
                'precio_venta'  => 4200,
                'stock_actual'  => 100,
                'stock_minimo'  => 20,
            ],
            [
                'codigo'        => 'CON003',
                'codigo_barras' => '7704001000031',
                'nombre'        => 'Sal Marina 500g',
                'categoria'     => 'Condimentos y Salsas',
                'unidad'        => $g,
                'iva'           => $excluido,
                'precio_compra' => 700,
                'precio_venta'  => 1200,
                'stock_actual'  => 80,
                'stock_minimo'  => 20,
            ],
            [
                'codigo'        => 'CON004',
                'codigo_barras' => '7704001000048',
                'nombre'        => 'Salsa de Tomate Fruco 400g',
                'categoria'     => 'Condimentos y Salsas',
                'unidad'        => $g,
                'iva'           => $excluido,
                'precio_compra' => 3200,
                'precio_venta'  => 4800,
                'stock_actual'  => 60,
                'stock_minimo'  => 12,
            ],

            // ── Bebidas ───────────────────────────────────────────────────
            [
                'codigo'        => 'BEB001',
                'codigo_barras' => '7705001000019',
                'nombre'        => 'Coca-Cola 600ml',
                'categoria'     => 'Gaseosas y Refrescos',
                'unidad'        => $ml,
                'iva'           => $iva19,
                'precio_compra' => 1800,
                'precio_venta'  => 3000,
                'stock_actual'  => 144,
                'stock_minimo'  => 24,
            ],
            [
                'codigo'        => 'BEB002',
                'codigo_barras' => '7705001000026',
                'nombre'        => 'Sprite 600ml',
                'categoria'     => 'Gaseosas y Refrescos',
                'unidad'        => $ml,
                'iva'           => $iva19,
                'precio_compra' => 1800,
                'precio_venta'  => 3000,
                'stock_actual'  => 96,
                'stock_minimo'  => 24,
            ],
            [
                'codigo'        => 'BEB003',
                'codigo_barras' => '7705001000033',
                'nombre'        => 'Postobon Manzana 500ml',
                'categoria'     => 'Gaseosas y Refrescos',
                'unidad'        => $ml,
                'iva'           => $iva19,
                'precio_compra' => 1600,
                'precio_venta'  => 2500,
                'stock_actual'  => 120,
                'stock_minimo'  => 24,
            ],
            [
                'codigo'        => 'BEB004',
                'codigo_barras' => '7705001000040',
                'nombre'        => 'Agua Cristal 600ml',
                'categoria'     => 'Agua',
                'unidad'        => $ml,
                'iva'           => $excluido,
                'precio_compra' => 900,
                'precio_venta'  => 1800,
                'stock_actual'  => 200,
                'stock_minimo'  => 48,
            ],
            [
                'codigo'        => 'BEB005',
                'codigo_barras' => '7705001000057',
                'nombre'        => 'Jugo Hit Naranja 200ml',
                'categoria'     => 'Jugos Naturales',
                'unidad'        => $ml,
                'iva'           => $iva5,
                'precio_compra' => 900,
                'precio_venta'  => 1500,
                'stock_actual'  => 100,
                'stock_minimo'  => 24,
            ],
            [
                'codigo'        => 'BEB006',
                'codigo_barras' => '7705001000064',
                'nombre'        => 'Café Águila Roja 125g',
                'categoria'     => 'Café y Té',
                'unidad'        => $g,
                'iva'           => $excluido,
                'precio_compra' => 4800,
                'precio_venta'  => 7200,
                'stock_actual'  => 50,
                'stock_minimo'  => 10,
            ],

            // ── Snacks y Confitería ───────────────────────────────────────
            [
                'codigo'        => 'SNA001',
                'codigo_barras' => '7706001000015',
                'nombre'        => 'Papas Margarita Sal x 85g',
                'categoria'     => 'Snacks y Confitería',
                'unidad'        => $g,
                'iva'           => $iva19,
                'precio_compra' => 2500,
                'precio_venta'  => 4200,
                'stock_actual'  => 80,
                'stock_minimo'  => 12,
            ],
            [
                'codigo'        => 'SNA002',
                'codigo_barras' => '7706001000022',
                'nombre'        => 'Galletas Festival x200g',
                'categoria'     => 'Snacks y Confitería',
                'unidad'        => $g,
                'iva'           => $iva5,
                'precio_compra' => 3200,
                'precio_venta'  => 5500,
                'stock_actual'  => 60,
                'stock_minimo'  => 12,
            ],
            [
                'codigo'        => 'SNA003',
                'codigo_barras' => '7706001000039',
                'nombre'        => 'Chocolate Jet x180g',
                'categoria'     => 'Snacks y Confitería',
                'unidad'        => $g,
                'iva'           => $iva5,
                'precio_compra' => 5500,
                'precio_venta'  => 8500,
                'stock_actual'  => 40,
                'stock_minimo'  => 8,
            ],
            [
                'codigo'        => 'SNA004',
                'codigo_barras' => '7706001000046',
                'nombre'        => 'Bon Bon Bum Fresa x24',
                'categoria'     => 'Snacks y Confitería',
                'unidad'        => $un,
                'iva'           => $iva5,
                'precio_compra' => 5000,
                'precio_venta'  => 8000,
                'stock_actual'  => 30,
                'stock_minimo'  => 6,
            ],

            // ── Aseo y Limpieza ───────────────────────────────────────────
            [
                'codigo'        => 'ASE001',
                'codigo_barras' => '7707001000012',
                'nombre'        => 'Jabón Barra Palmolive x3',
                'categoria'     => 'Aseo y Limpieza',
                'unidad'        => $un,
                'iva'           => $iva19,
                'precio_compra' => 5800,
                'precio_venta'  => 9500,
                'stock_actual'  => 60,
                'stock_minimo'  => 12,
            ],
            [
                'codigo'        => 'ASE002',
                'codigo_barras' => '7707001000029',
                'nombre'        => 'Detergente Ariel 1kg',
                'categoria'     => 'Aseo y Limpieza',
                'unidad'        => $kg,
                'iva'           => $iva19,
                'precio_compra' => 12000,
                'precio_venta'  => 18500,
                'stock_actual'  => 40,
                'stock_minimo'  => 8,
            ],
            [
                'codigo'        => 'ASE003',
                'codigo_barras' => '7707001000036',
                'nombre'        => 'Desinfectante Fabuloso 1L',
                'categoria'     => 'Aseo y Limpieza',
                'unidad'        => $lt,
                'iva'           => $iva19,
                'precio_compra' => 5500,
                'precio_venta'  => 9000,
                'stock_actual'  => 50,
                'stock_minimo'  => 10,
            ],
            [
                'codigo'        => 'ASE004',
                'codigo_barras' => '7707001000043',
                'nombre'        => 'Papel Higiénico Scott x4',
                'categoria'     => 'Aseo y Limpieza',
                'unidad'        => $un,
                'iva'           => $excluido,
                'precio_compra' => 5200,
                'precio_venta'  => 8500,
                'stock_actual'  => 80,
                'stock_minimo'  => 20,
            ],

            // ── Cuidado Personal ──────────────────────────────────────────
            [
                'codigo'        => 'CUI001',
                'codigo_barras' => '7708001000018',
                'nombre'        => 'Shampoo Head & Shoulders 400ml',
                'categoria'     => 'Cuidado Personal',
                'unidad'        => $ml,
                'iva'           => $iva19,
                'precio_compra' => 14000,
                'precio_venta'  => 22000,
                'stock_actual'  => 30,
                'stock_minimo'  => 6,
            ],
            [
                'codigo'        => 'CUI002',
                'codigo_barras' => '7708001000025',
                'nombre'        => 'Crema Dental Colgate 75ml',
                'categoria'     => 'Cuidado Personal',
                'unidad'        => $ml,
                'iva'           => $excluido,
                'precio_compra' => 3800,
                'precio_venta'  => 6500,
                'stock_actual'  => 50,
                'stock_minimo'  => 12,
            ],
            [
                'codigo'        => 'CUI003',
                'codigo_barras' => '7708001000032',
                'nombre'        => 'Desodorante Axe 150ml',
                'categoria'     => 'Cuidado Personal',
                'unidad'        => $ml,
                'iva'           => $iva19,
                'precio_compra' => 9500,
                'precio_venta'  => 16000,
                'stock_actual'  => 30,
                'stock_minimo'  => 6,
            ],

            // ── Frutas y Verduras ─────────────────────────────────────────
            [
                'codigo'        => 'FRU001',
                'codigo_barras' => null,
                'nombre'        => 'Tomate Chonto x Kg',
                'categoria'     => 'Frutas y Verduras',
                'unidad'        => $kg,
                'iva'           => $excluido,
                'precio_compra' => 1800,
                'precio_venta'  => 3500,
                'stock_actual'  => 50,
                'stock_minimo'  => 10,
            ],
            [
                'codigo'        => 'FRU002',
                'codigo_barras' => null,
                'nombre'        => 'Cebolla Cabezona x Kg',
                'categoria'     => 'Frutas y Verduras',
                'unidad'        => $kg,
                'iva'           => $excluido,
                'precio_compra' => 1500,
                'precio_venta'  => 2800,
                'stock_actual'  => 30,
                'stock_minimo'  => 8,
            ],
            [
                'codigo'        => 'FRU003',
                'codigo_barras' => null,
                'nombre'        => 'Papa Pastusa x Kg',
                'categoria'     => 'Frutas y Verduras',
                'unidad'        => $kg,
                'iva'           => $excluido,
                'precio_compra' => 1200,
                'precio_venta'  => 2200,
                'stock_actual'  => 80,
                'stock_minimo'  => 20,
            ],
            [
                'codigo'        => 'FRU004',
                'codigo_barras' => null,
                'nombre'        => 'Banano Criollo x Kg',
                'categoria'     => 'Frutas y Verduras',
                'unidad'        => $kg,
                'iva'           => $excluido,
                'precio_compra' => 1200,
                'precio_venta'  => 2000,
                'stock_actual'  => 40,
                'stock_minimo'  => 10,
            ],
        ];

        foreach ($productos as $data) {
            $categoria = $cat($data['categoria']);

            Producto::firstOrCreate(
                ['codigo' => $data['codigo']],
                [
                    'codigo_barras'   => $data['codigo_barras'],
                    'nombre'          => $data['nombre'],
                    'categoria_id'    => $categoria?->id,
                    'unidad_medida_id' => $data['unidad']?->id,
                    'tarifa_iva_id'   => $data['iva']?->id,
                    'precio_compra'   => $data['precio_compra'],
                    'precio_venta'    => $data['precio_venta'],
                    'precio_mayorista' => round($data['precio_venta'] * 0.9),
                    'stock_actual'    => $data['stock_actual'],
                    'stock_minimo'    => $data['stock_minimo'],
                    'activo'          => true,
                ]
            );
        }
    }
}
